### PR TITLE
Error: Puppet::Util::FileType::FileTypeFlat could not read absent fix

### PR DESCRIPTION
**Pull request by bryanjbelanger**
While running Puppet we got this error:

Error: Puppet::Util::FileType::FileTypeFlat could not read absent: FileSystem implementation expected Pathname, got: 'Symbol'

The exception occurs in the file puppet/file_system/file_impl.rb:

def assert_path(path)
return path if path.is_a?(Pathname)

``` ruby
# Some paths are string, or in the case of WatchedFile, it pretends to be
# one by implementing to_str.
if path.respond_to?(:to_str)
  Pathname.new(path)
else
  raise ArgumentError, "FileSystem implementation expected Pathname, got: '#{path.class}'"
end
```

end

The solution does the same checks as assert_path. If the checks do not pass we do not go further since an exception will be raised.

### CODE REVIEW

**Comment by jyaworski** [comment]
Hey @bryanjbelanger. Can you rebase against the current master and squash?

**Comment by bastelfreak** [comment]
ping @bryanjbelanger. could you please rebase?

**Comment by bryanjbelanger** [comment]
Done.

On Jun 5, 2016, at 9:07 AM, Tim Meusel <notifications@github.com<mailto:notifications@github.com>> wrote:


ping @bryanjbelanger<https://github.com/bryanjbelanger>. could you please rebase?

**Comment by rski** [comment]
@bryanjbelanger did you rebase or merge master?
(btw I removed a sensitive link from the reply)

**Comment by bastelfreak** [comment]
closing this in favor of https://github.com/voxpupuli/puppet-filemapper/pull/33

**Pull request closed without merging**
