### PR TITLE
Update based on voxpupuli/modulesync_config 0.14.1. This might fix #27

### PR DESCRIPTION
**Pull request by dhoppe**

### CODE REVIEW

**Comment by dhoppe** [comment]
Puppet 4 will complain about too many expectations and nested groups etc.

**Comment by bastelfreak** [comment]
@dhoppe I think we should temporarily disable the cops in that single file, create an issue which reminds us to fix it alter, and than proceed with this PR and merge it?

**Comment by dhoppe** [comment]
@bastelfreak You already created an [issue](https://github.com/voxpupuli/puppet-filemapper/issues/25) regarding this topic.

**Comment by bastelfreak** [comment]
nice :D

**Pull request merged**
